/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projek_pbo;

import javax.swing.JOptionPane;
import java.sql.*;
import database.Config;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;
/**
 *
 * @author NANANG TRI HANDOYO
 */
public class Data extends Menu {
    
    Connection conn;
    Statement stmt;
    ResultSet rs;
    
    Config koneksi;

    public JComboBox<String> getCombo_fk() {
        return combo_fk;
    }

    public JComboBox<String> getCombo_pr() {
        return combo_pr;
    }

    public JTextField getTxt_alamat() {
        return txt_alamat;
    }

    public JTextField getTxt_nama() {
        return txt_nama;
    }

    public JTextField getTxt_nim() {
        return txt_nim;
    }
    
    String nim, nama, alamat, fakultas, prodi, idFk, idPr;
    /**
     * Creates new form Data
     */
    public Data() {
        initComponents();
        
        setVisible(true);
        koneksi = new Config();
        conn = koneksi.getConnection();  
    }

    public JButton getBtn_submit() {
        return btn_submit;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_datamhs = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_nim = new javax.swing.JTextField();
        txt_alamat = new javax.swing.JTextField();
        txt_nama = new javax.swing.JTextField();
        combo_fk = new javax.swing.JComboBox<>();
        combo_pr = new javax.swing.JComboBox<>();
        btn_submit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_tampil = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel_datamhs.setBorder(javax.swing.BorderFactory.createTitledBorder("Data Mahasiswa"));

        jLabel1.setText("NIM");

        jLabel2.setText("Nama");

        jLabel3.setText("Alamat");

        jLabel4.setText("Prodi");

        jLabel5.setText("Fakultas");

        txt_nim.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_nimFocusLost(evt);
            }
        });
        txt_nim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nimActionPerformed(evt);
            }
        });

        txt_nama.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txt_namaFocusLost(evt);
            }
        });

        combo_fk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Fakultas", "FTI", "FISIP", "FTM" }));
        combo_fk.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                combo_fkFocusLost(evt);
            }
        });
        combo_fk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_fkActionPerformed(evt);
            }
        });

        combo_pr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                combo_prFocusLost(evt);
            }
        });

        btn_submit.setBackground(new java.awt.Color(204, 204, 204));
        btn_submit.setText("Submit");

        jTextArea_tampil.setBackground(javax.swing.UIManager.getDefaults().getColor("control"));
        jTextArea_tampil.setColumns(20);
        jTextArea_tampil.setRows(5);
        jTextArea_tampil.setAlignmentX(0.0F);
        jTextArea_tampil.setAlignmentY(0.0F);
        jTextArea_tampil.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextArea_tampil.setMargin(new java.awt.Insets(0, 0, 0, 0));
        jScrollPane1.setViewportView(jTextArea_tampil);

        javax.swing.GroupLayout jPanel_datamhsLayout = new javax.swing.GroupLayout(jPanel_datamhs);
        jPanel_datamhs.setLayout(jPanel_datamhsLayout);
        jPanel_datamhsLayout.setHorizontalGroup(
            jPanel_datamhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_datamhsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel_datamhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel_datamhsLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_datamhsLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_datamhsLayout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(combo_fk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_datamhsLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_nim, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel_datamhsLayout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel_datamhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_datamhsLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(combo_pr, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel_datamhsLayout.createSequentialGroup()
                                .addGap(172, 172, 172)
                                .addComponent(btn_submit)))))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(jPanel_datamhsLayout.createSequentialGroup()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel_datamhsLayout.setVerticalGroup(
            jPanel_datamhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_datamhsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_datamhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_datamhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_datamhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txt_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_datamhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(combo_fk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_datamhsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(combo_pr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_submit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_datamhs, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_datamhs, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt_namaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_namaFocusLost
        // TODO add your handling code here:
        checkNama();
    }//GEN-LAST:event_txt_namaFocusLost

    private void txt_nimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nimActionPerformed

    private void txt_nimFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txt_nimFocusLost
        // TODO add your handling code here:
        checkNIM();
    }//GEN-LAST:event_txt_nimFocusLost

    private void combo_prFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_combo_prFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_prFocusLost

    private void combo_fkFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_combo_fkFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_fkFocusLost

    private void combo_fkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_fkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo_fkActionPerformed

    /**
     * @param args the command line arguments
     */
    
    private void checkNama(){
    boolean checkNama;
    nama = txt_nama.getText().toString();
    String errorNama = "Nama hanya terdiri dari karakter huruf A-Z";
    
    checkNama = nama.matches("[a-zA-Z\s]+");
    
    if (checkNama == false){
        jTextArea_tampil.setText(errorNama);}
    }
    
    private void checkNIM(){
    boolean checkNIM;
    nim = txt_nim.getText().toString();
    String errorNIM = "NIM hanya terdiri dari angka sebanyak 9 digit!";
    
    checkNIM = nim.matches("^[0-9]{9}$");
    
    if (checkNIM == false){
        jTextArea_tampil.setText(errorNIM);}
    }
     
    private void setProdi(){
         if(combo_fk.getSelectedItem().toString().equalsIgnoreCase("FTI")){
          combo_pr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Informatika", "Sistem Informasi" }));
         }else if(combo_fk.getSelectedItem().toString().equalsIgnoreCase("FISIP")){
          combo_pr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hubungan Internasional", "Sosiologi" }));
         }else if(combo_fk.getSelectedItem().toString().equalsIgnoreCase("FTM")){
          combo_pr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Perminyakan", "Pertambangan" }));
         }else{
          combo_pr.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "" }));
 }
}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_submit;
    private javax.swing.JComboBox<String> combo_fk;
    private javax.swing.JComboBox<String> combo_pr;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel_datamhs;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_tampil;
    private javax.swing.JTextField txt_alamat;
    private javax.swing.JTextField txt_nama;
    private javax.swing.JTextField txt_nim;
    // End of variables declaration//GEN-END:variables
}
