/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projek_pbo;

import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author NANANG TRI HANDOYO
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        //JOptionPane.showMessageDialog(null, "Berhasil Login");
        setVisible(true);

    }

    public JMenuItem getjMenuItemExit() {
        return jMenuItemExit;
    }

    public JMenuItem getjMenuItemLogout() {
        return jMenuItemLogout;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuAkun = new javax.swing.JMenu();
        jMenuItemLogout = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenuData = new javax.swing.JMenu();
        jMenuItemIsi = new javax.swing.JMenuItem();
        jMenuItemArsip = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenuAkun.setText("Akun");

        jMenuItemLogout.setText("Logout");
        jMenuAkun.add(jMenuItemLogout);

        jMenuItemExit.setText("Exit");
        jMenuAkun.add(jMenuItemExit);

        jMenuBar1.add(jMenuAkun);

        jMenuData.setText("Data");

        jMenuItemIsi.setText("Isi Data Mahasiswa");
        jMenuData.add(jMenuItemIsi);

        jMenuItemArsip.setText("Arsip Data Mahasiswa");
        jMenuData.add(jMenuItemArsip);

        jMenuItem1.setText("Cetak Data");
        jMenuData.add(jMenuItem1);

        jMenuBar1.add(jMenuData);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 411, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public JMenuItem getjMenuItem1() {
        return jMenuItem1;
    }

    public JMenuItem getjMenuItemArsip() {
        return jMenuItemArsip;
    }

    /**
     * @param args the command line arguments
     */
    public JMenuItem getjMenuItemIsi() {
        return jMenuItemIsi;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAkun;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuData;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemArsip;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemIsi;
    private javax.swing.JMenuItem jMenuItemLogout;
    // End of variables declaration//GEN-END:variables

   }